### ISSUE TITLE
How to slide next View Controller on button Click.

### ISSUE THREAD

**Issue by jakirkhan819408** [DeluxeAlonso/DLAutoSlidePageViewController#30]
Hi ,
I am not able to slide view controller on click on any event. because I want to slide on button click.
Please give me solution for this asap.

Thanks

**Comment by DeluxeAlonso** [comment]
Hi @jakirkhan819408, slide when page control is tapped is supported (if you tap the page control indicators it should slide the page view controller). Is that not working for you?

If what you want is to slide back/forward the page controller when the page controller is tapped on the sides, that is not supported yet, sadly. I might add that feature in the future.

**Comment by DeluxeAlonso** [comment]
@jakirkhan819408 I added the support for slide on tap. Now if you tap on the left of the page controller it will slide back. If you tap on the right of the page controller it will slide forward. To enable this you need to set `shouldSlideOnTap` configuration property to true:

`DefaultAutoSlideConfiguration.shared.shouldSlideOnTap = true`

To have this feature, you need to use at least version 3.0.0 of the library.

**Comment by jakirkhan819408** [comment]
Thanks DeluxeAlonso/DLAutoSlidePageViewController

**Comment by jakirkhan819408** [comment]
Hi Dear,

I need to remove bottom paging area getting 70 height from bottom so how
remove that space kindly help me please.

Thanks

**Comment by DeluxeAlonso** [comment]
Hi @jakirkhan819408, if you are talking about hiding the page control (page dots), you can try:
`DefaultAutoSlideConfiguration.shared.hidePageControl = true`

If you are talking about something different, can you upload some example project or screenshot of your issue?

**Comment by jakirkhan819408** [comment]
I have hide dots but getting space in bottom.

**Comment by DeluxeAlonso** [comment]
Maybe there are some issues with your layout.
When I do `DefaultAutoSlideConfiguration.shared.hidePageControl = true` page control is hidden and no extra space is there.

|**hidePageControl = false**| **hidePageControl = true** |
|--------|-------|
| ![PageControl](https://github.com/DeluxeAlonso/DLAutoSlidePageViewController/assets/9066633/b39ee24c-557c-48d9-9139-d19614505391)| ![Simulator Screenshot - iPhone 14 Pro - 2024-01-17 at 01 26 20](https://github.com/DeluxeAlonso/DLAutoSlidePageViewController/assets/9066633/6ef0d032-d6be-45b0-b1d1-8269737aa5ec)|

Can you upload an example project where you are facing that issue? So I can take a look when I have a chance.

**Comment by jakirkhan819408** [comment]
Ok I am checking at my and let me know if get any issues

**Comment by jakirkhan819408** [comment]
In bottom I want to print the current index on Base VC. How to print
current index when sliding

**Comment by DeluxeAlonso** [comment]
@jakirkhan819408 Im adding a new property to DLAutoSlidePageViewController class:  https://github.com/DeluxeAlonso/DLAutoSlidePageViewController/pull/50

Once it is merged you will be able to get the current index by doing:

```
pageViewController.currentPageIndexDidChange = { _, newIndex in
       print(newIndex)
}
```

Will let you know when it gets merged.

**Comment by DeluxeAlonso** [comment]
@jakirkhan819408 Changes were pushed.
To use the new `currentPageIndexDidChange` property you need to use at least version `3.2.0` of the library.

```
pageViewController.currentPageIndexDidChange = { _, newIndex in
       print(newIndex)
}
```
